title: PxN
description: PxN pipeline
theme: just-the-docs

url: https://hidelab.github.io/pxn

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/hidelab/pxn
